import React from 'react';
import { View, Text } from 'react-native';
import { useTheme } from '@/Hooks'
import { VeroHeader, VeroText } from '@/Components';
import { useTranslation } from 'react-i18next'
import { WP } from '@/Theme/Responsive';



const TermsConditions = () => {
    const { Layout } = useTheme()
    const { t } = useTranslation()

  return (
      <View style={Layout.fill}>
      <VeroHeader title={t("terms")}/>
        <VeroText text="
        Last Updated:  April 1, 2022
These Terms of Service constitute a legally binding agreement (the “Agreement”) between you and Vero 1 , Inc., its parents, subsidiaries, representatives, affiliates, officers and directors (collectively, “Vero 1 ,” “we,” “us” or “our”) governing your use of the Vero 1  application (the “Vero 1  App”), website, and technology platform (collectively, the “Vero 1  Platform”). 
Please be advised: This Agreement contains provisions that govern how claims between you and Vero 1  can be brought (see Section 17 below). These provisions will, with limited exception, require you to submit claims you have against Vero 1  to binding and final arbitration on an individual basis, not as a plaintiff or class member in any class, group or representative action or proceeding. As a Driver or Driver applicant, you have an opportunity to opt out of arbitration with respect to certain claims as provided in Section 17. 
By entering into this Agreement, and/or by using or accessing the Vero 1  Platform you expressly acknowledge that you understand this Agreement (including the dispute resolution and arbitration provisions in Section 17) and accept all of its terms. If you do not agree to be bound by the terms and conditions of this Agreement, you may not use or access the Vero 1  Platform or any of the services provided through the Vero 1  Platform. If you use the Vero 1  Platform in another country, you agree to be subject to Vero 1 's terms of service for that country. 
When using the Vero 1  Platform, you also agree to conduct yourself in accordance with our Community Guidelines, which shall form part of this Agreement between you and Vero 1 . 
The Vero 1  Platform
The Vero 1 Platform provides a marketplace where, among numerous on demand services, persons who seek transportation to certain destinations (“Riders”) can be matched with transportation options to such destinations. One option for Riders is to request a ride from rideshare drivers who are driving to or through those destinations (“Drivers”). Drivers and Riders are collectively referred to herein as “Users,” and the driving services provided by Drivers to Riders shall be referred to herein as “Rideshare Services.” As a User, you authorize Vero 1  to match you with Drivers or Riders based on factors such as your location, the requested pickup location, the estimated time to pickup, your destination, User preferences, driver mode, and platform efficiency, and to cancel an existing match and/or rematch you with a Driver or Rider based on the same considerations. Any decision by a User to offer or accept Rideshare Services is a decision made in such User’s sole discretion. Each Rideshare Service provided by a Driver to a Rider shall constitute a separate agreement between such persons. 
Modification to the Agreement
Vero 1  reserves the right to modify the terms and conditions of this Agreement, and such modifications shall be binding on you only upon your acceptance of the modified Agreement. Vero 1  reserves the right to modify any information on pages referenced in the hyperlinks from this Agreement from time to time, and such modifications shall become effective upon posting. Continued use of the Vero 1  Platform or Rideshare Services after any such changes shall constitute your consent to such changes. Unless material changes are made to the arbitration provisions herein, you agree that modification of this Agreement does not create a renewed opportunity to opt out of arbitration (if applicable). 
Eligibility
The Vero 1  Platform may only be used by individuals who have the right and authority to enter into this Agreement and are fully able and competent to satisfy the terms, conditions, and obligations herein. The Vero 1  Platform is not available to Users who have had their User account temporarily or permanently deactivated. You may not allow other persons to use your User account, and you agree that you are the sole authorized user of your account. To use the Vero 1  Platform, each User shall create a User account. Each person may only create one User account, and Vero 1  reserves the right to deactivate any additional or duplicate accounts. Your participation in certain Vero 1  programs and use of certain Vero 1  products or services may be subject to additional eligibility requirements as determined by Vero 1 . 
By becoming a User, you represent and warrant that you are at least 18 years old. 
Charges
As a Rider, you understand that request or use of Rideshare Services may result in charges to you (“Charges”). Charges related to bikes and scooters are addressed in the applicable Supplemental Agreement. Charges for Rideshare Services include Fares and other applicable fees, tolls, surcharges, and taxes as set forth on your market’s Vero 1  Cities page (www.Vero 1 .com/cities), plus any tips to the Driver that you elect to pay. Vero 1  has the authority and reserves the right to determine and modify pricing by posting applicable pricing terms to your market’s Vero 1  Cities page or quoting you a price for a specific ride at the time you make a request. Pricing may vary based on the type of service you request (e.g., shared, economy, extra seats, luxury) as described on your market’s Vero 1  Cities page. You are responsible for reviewing the applicable Vero 1  Cities page or price quote within the Vero 1  App and shall be responsible for all Charges incurred under your User account regardless of your awareness of such Charges or the amounts thereof. 
Fares. There are two types of Fares, variable and quoted. 
•	Variable Fares. Variable fares consist of a base charge and incremental charges based on the duration and distance of your ride and the average price of gas/petrol in your geographic region. For particularly short rides, minimum fares may apply. Please note that we use GPS data from your Driver’s phone to calculate the distance traveled on your ride. We cannot guarantee the availability or accuracy of GPS data. If we lose signal we will calculate time and distance using available data from your ride. 
•	Quoted Fares. In some cases Vero 1  may quote you a Fare at the time of your request. The quote is subject to change until the ride request is confirmed. If during your ride you change your destination, make multiple stops, or attempt to abuse the Vero 1  Platform, we may cancel the fare quote and charge you a variable fare based on the time and distance of your ride. Vero 1  does not guarantee that the quoted fare price will be equal to a variable fare for the same ride. Quoted Fares may include the Fees and Other Charges below, as applicable. 
Fees and Other Charges. 
•	Service Fee. You may be charged a “Service Fee” for each ride as set forth on the applicable Vero 1 Cities page. 
•	Prime Time. At certain times, including peak times of high demand for Rideshare Services (“Prime Time”), you acknowledge that Charges may increase substantially. For all rides with a variable fare, we will use reasonable efforts to inform you of any Prime Time increases in effect at the time of your request. For Quoted Fares we may factor in the Prime Time increases into the quoted price of the ride. 
•	Cancellation Fee. After requesting a ride you may cancel it through the Vero 1  App, but note that in certain cases a cancellation fee may apply if the ride is not cancelled within [  ] minutes after the request is made. You may also be charged if you fail to show up after requesting a ride. Please check out our Help Center to learn more about Vero 1 ’s cancellation policy, including applicable fees. 
•	Damage Fee. If a Driver reports that you have materially damaged the Driver's vehicle, you agree to pay a “Damage Fee” of up to $250 depending on the extent of the damage (as determined by Vero 1 in its sole discretion), towards vehicle repair or cleaning. Vero 1  reserves the right (but is not obligated) to verify or otherwise require documentation of damages prior to processing the Damage Fee. 
•	Tolls. In some instances tolls (or return tolls) may apply to your ride. Please see our Help Center and your market’s Vero 1  Cities page for more information about toll charges and a list of applicable tolls and return charges. We do not guarantee that the amount charged by Vero 1  will match the toll charged to the Driver, if any. 
•	Other Charges. Other fees and surcharges may apply to your ride, including: actual or anticipated airport fees, state or local fees, or event fees as determined by Vero 1  or its marketing partners. In addition, where required by law Vero 1  will collect applicable taxes. See your market’s Vero 1  Cities page for details on other Charges that may apply to your ride. 
•	Tips. Following a ride, you may elect to tip your Driver in cash or through the Vero 1  Platform. You may also elect to set a default tip amount or percentage through the Vero 1  App. Any tips will be provided entirely to the applicable Driver. 
•	Vero 1 Pass and Pass Plus.   You may receive a discount on your ride if you are an active Vero 1 Pass or Pass+ subscriber. 
General. 
•	Facilitation of Charges. All Charges are facilitated through a third-party payment processor (e.g., First Data, Stripe, Inc., or Braintree, a division of PayPal, Inc.). Vero 1  may replace its third-party payment processor without notice to you. Charges shall only be made through the Vero 1  Platform. With the exception of tips, cash payments are strictly prohibited. Your payment of Charges to Vero 1  satisfies your payment obligation for your use of the Vero 1  Platform and Rideshare Services. Certain Charges may be collectively billed as a single purchase transaction to your selected payment method based on the payment frequency indicated in your settings. If you don't recognize a transaction, then check your ride receipts and payment history. 
•	No Refunds. All Charges are non-refundable. This no-refund policy shall apply at all times regardless of your decision to terminate usage of the Vero 1 Platform, any disruption to the Vero 1  Platform or Rideshare Services, or any other reason whatsoever. 
•	Coupons. You may receive coupons that you can apply toward payment of certain Charges upon completion of a Ride. Coupons are only valid for use on the Vero 1  Platform, and are not transferable or redeemable for cash except as required by law. Coupons cannot be combined unless expressly provided otherwise, and if the cost of your ride exceeds the applicable credit or discount value we will charge your payment method on file for the outstanding cost of the Ride. For quoted or variable fares, Vero 1  may deduct the amount attributable to the Service Fee, Tolls, or Other Charges before application of the coupon. Additional restrictions on coupons may apply as communicated to you in a relevant promotion or by clicking on the relevant coupon within the Promotions section of the Vero 1  App. 
•	Credit Card Authorization. Upon addition of a new payment method or each ride request, Vero 1  may seek authorization of your selected payment method to verify the payment method, ensure the ride cost will be covered, and protect against unauthorized behavior. The authorization is not a charge, however, it may reduce your available credit by the authorization amount until your bank’s next processing cycle. Should the amount of our authorization exceed the total funds on deposit in your account, you may be subject to overdraft of NSF charges by the bank issuing your debit or prepaid card. We cannot be held responsible for these charges and are unable to assist you in recovering them from your issuing bank. Check out our Help Center to learn more about our use of pre-authorization holds. 
•	Disputes.  Vero 1 has a dedicated customer support and dispute resolution team that investigates and handles all transaction and misconduct disputes.  Vero 1 takes all such disputes and complaints filed by users and drivers very seriously.  Vero 1 will make appropriate credits and adjustments to your account that are warranted by the facts and evidence upon a complete review and determination of the team’s investigation.  You may be contacted and asked to provide additional information and documents.  Note however that Vero 1 has a zero-tolerance policy for any user that abuses use of its Platform, Vero 1 drivers, passengers, or engages in any type of fraudulent conduct.  You agree and understand that if you request, accept, and receive the benefits of a service that has been performed and completed by your Vero 1 driver, the authorized charge to your credit card is valid.  If you attempt to obtain free services through a fraudulent charge back, your account will be terminated.  You agree to pay Vero 1 for all fees, costs, and charges that are incurred and determined to be valid through a reversal of the chargeback by your credit card issuer.  

Payments
If you are a Driver, you will receive payment for your provision of Rideshare Services pursuant to the terms of the Driver Addendum, which shall form part of this Agreement between you and Vero 1 . 
Vero 1  Communications
By entering into this Agreement or using the Vero 1  Platform, you agree to receive communications from us or communications related to the Vero 1  Platform at any of the phone numbers provided to Vero 1  by you or on your behalf, including via e-mail, text message, calls, and push notifications. You agree that texts, calls or prerecorded messages may be generated by automatic telephone dialing systems. Communications from Vero 1 , its affiliated companies and/or Drivers, may include but are not limited to: operational communications concerning your User account or use of the Vero 1  Platform or Rideshare Services, use of bikes and scooters through the Vero 1 Platform, updates concerning new and existing features on the Vero 1  Platform, communications concerning marketing or promotions run by us or our third-party partners, and news concerning Vero 1  and industry developments. If you change or deactivate the phone number you provided to Vero 1 , you agree to update your account information to help prevent us from inadvertently communicating with anyone who acquires your old number. Standard text messaging charges applied by your cell phone carrier will apply to text messages we send. 
If you wish to opt out of promotional emails, you can unsubscribe from our promotional email list by following the unsubscribe options in the promotional email itself. If you wish to opt out of promotional calls or texts, you may text “END” to 46080 from the mobile device receiving the messages. You acknowledge that you are not required to consent to receive promotional texts or calls as a condition of using the Vero 1  Platform or related services. If you wish to opt out of all texts or calls from Vero 1  (including operational or transactional texts or calls), you can text the word “STOPALL” to [               ] from the mobile device receiving the messages, however you acknowledge that opting out of receiving all texts may impact your use of the Vero 1  Platform or related services. 
Your Information
Your Information is any information you provide, publish or post to or through the Vero 1  Platform (including any profile information you provide) or send to other Users (including via in-application feedback, any email feature, or through any Vero 1 -related Facebook, Twitter or other social media posting) (your “Information”). You consent to us using your Information to create a User account that will allow you to use the Vero 1  Platform and participate in the Rideshare Services. Our collection and use of personal information in connection with the Vero 1  Platform and Rideshare Services is as provided in Vero 1 ’s Privacy Policy located at www.Vero 1 .com/privacy. You are solely responsible for your Information and your interactions with other members of the public, and we act only as a passive conduit for your online posting of your Information. You agree to provide and maintain accurate, current and complete information and that we and other members of the public may rely on your Information as accurate, current and complete. To enable Vero 1  to use your Information for the purposes described in the Privacy Policy and this Agreement, you grant to us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, transferable, sub-licensable (through multiple tiers) right and license to exercise the copyright, publicity, and database rights you have in your Information, and to use, copy, perform, display and distribute such Information to prepare derivative works, or incorporate into other works, such Information, in any media now known or not currently known. Vero 1  does not assert any ownership over your Information; rather, as between you and Vero 1 , subject to the rights granted to us in this Agreement, you retain full ownership of all of your Information and any intellectual property rights or other proprietary rights associated with your Information. 
Promotions, Referrals, and Loyalty Programs
Vero 1, at its sole discretion, may make available promotions, referral programs and loyalty programs with different features to any Users or prospective Users. These promotions and programs, unless made to you, shall have no bearing whatsoever on your Agreement or relationship with Vero 1. Vero 1  reserves the right to withhold or deduct credits or benefits obtained through a promotion or program in the event that Vero 1  determines or believes that the redemption of the promotion or receipt of the credit or benefit was in error, fraudulent, illegal, or in violation of the applicable promotion or program terms or this Agreement. Vero 1  reserves the right to terminate, discontinue or cancel any promotions or programs at any time and in its sole discretion without notice to you. 
Currently, Vero 1 ’s referral program provides you with incentives to refer your friends and family to become new Users of the Vero 1  Platform in your country (the “Referral Program”). Your participation in the Referral Program is subject to this Agreement and the additional Referral Program rules. 
Restricted Activities
With respect to your use of the Vero 1 Platform and your participation in the Rideshare Services, you agree that you will not: 
1.	impersonate any person or entity; 
2.	stalk, threaten, or otherwise harass any person, or carry any weapons; 
3.	violate any law, statute, rule, permit, ordinance or regulation; 
4.	interfere with or disrupt the Vero 1 Platform or the servers or networks connected to the Vero 1 Platform; 
5.	post Information, interact, or engage in conduct using the Vero 1 Platform or Rideshare Services in a manner which is fraudulent, libelous, abusive, obscene, profane, sexually oriented, harassing, or illegal; 
6.	use the Vero 1 Platform in any way that infringes any third party’s rights, including: intellectual property rights, copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy; 
7.	post, email or otherwise transmit any malicious code, files or programs designed to interrupt, damage, destroy or limit the functionality of the Vero 1  Platform or any computer software or hardware or telecommunications equipment or surreptitiously intercept or expropriate any system, data or personal information; 
8.	forge headers or otherwise manipulate identifiers in order to disguise the origin of any information transmitted through the Vero 1  Platform; 
9.	“frame” or “mirror” any part of the Vero 1  Platform, without our prior written authorization or use meta tags or code or other devices containing any reference to us in order to direct any person to any other web site for any purpose; 
10.	modify, adapt, translate, reverse engineer, decipher, decompile or otherwise disassemble any portion of the Vero 1  Platform; 
11.	rent, lease, lend, sell, redistribute, license or sublicense the Vero 1  Platform or access to any portion of the Vero 1  Platform; 
12.	use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, scrape, “data mine”, or in any way reproduce or circumvent the navigational structure or presentation of the Vero 1  Platform or its contents; 
13.	link directly or indirectly to any other web sites; 
14.	transfer or sell your User account, password and/or identification, or any other User's Information to any other party; 
15.	discriminate against or harass anyone on the basis of race, national origin, religion, gender, gender identity or expression, physical or mental disability, medical condition, marital status, age or sexual orientation; 
16.	violate any of the Referral Program rules if you participate in the Referral Program; or 
17.	cause any third party to engage in the restricted activities above. 
Driver Representations, Warranties and Agreements
By providing Rideshare Services as a Driver on the Vero 1  Platform, you represent, warrant, and agree that: 
1.	You possess a valid driver’s license and are authorized and medically fit to operate a motor vehicle and have all appropriate licenses, approvals and authority to provide transportation to Riders in all jurisdictions in which you provide Rideshare Services. 
2.	You own, or have the legal right to operate, the vehicle you use when providing Rideshare Services; such vehicle is in good operating condition and meets the industry safety standards and all applicable statutory and state department of motor vehicle requirements for a vehicle of its kind; and any and all applicable safety recalls have been remedied per manufacturer instructions. 
3.	You will not engage in reckless behavior while driving, drive unsafely, operate a vehicle that is unsafe to drive, permit an unauthorized third party to accompany you in the vehicle while providing Rideshare Services, provide Services as a Driver while under the influence of alcohol or drugs, or take action that harms or threatens to harm the safety of the Vero 1 community or third parties. 
4.	Within 30 days of being an approved Vero 1 driver, you agree to obtain and submit a vehicle inspection report for the vehicle you use to provide Ridesharing services from a Vero 1 approved auto inspection/repair facility, e.g,  PepBoys, Firestone, Goodyear, and Midas.  You cannot provide ridesharing services unless your vehicle passes inspection.
5.	You agree that while providing Vero 1 services you will wear an official Vero 1 cap that will be provided to you and/or Vero 1 official apparel (e.g, shirt or jacket) to identify yourself as a Vero 1 driver to Rideshare users which can be purchased from the Vero 1 Driver store.  
6.	You will only provide Rideshare Services using the vehicle that has been reported to, and approved by Vero 1, and for which a photograph has been provided to Vero 1 , and you will not transport more passengers than can securely be seated in such vehicle (and no more than seven (5) passengers in any instance). 
7.	You will not, while providing the Rideshare Services, operate as a public or common carrier or taxi service, accept street hails, charge for rides (except as expressly provided in this Agreement), demand that a rider pay in cash, or use a credit card reader, such as a Square Reader, to accept payment or engage in any other activity in a manner that is inconsistent with your obligations under this Agreement. 
8.	You will not attempt to defraud Vero 1 or Riders on the Vero 1  Platform or in connection with your provision of Rideshare Services. If we suspect that you have engaged in any type of fraudulent activity Vero 1 may withhold applicable fares or other payments for the ride(s) in question pending further investigation and take any other action against you available under the law, including, but not limited to, suspension and termination.
9.	You will not discriminate against Riders with disabilities and agree to review Vero 1 ’s Anti-Discrimination Policies. You will make reasonable accommodation as required by law and our Service Animal Policy and Wheelchair Policy for Riders who travel with their service animals or who use wheelchairs (or other mobility devices) that can be folded for safe and secure storage in the car’s trunk or backseat. 
10.	You agree that we may obtain information about you through background checks, third-parties, and law enforcement, including your criminal and driving records, and you agree to provide any further necessary authorizations to facilitate our access to such records during the term of the Agreement.  You agree that Vero 1 may verify any information on your application and any misrepresentation may be a basis by Vero 1 to suspend or terminate your Vero 1 driving access privileges.   
11.	You have and agree to maintain a valid policy of vehicle liability insurance (in coverage amounts consistent with all applicable legal requirements) that names or schedules you for the operation of the vehicle you use to provide Vero 1 Rideshare Services.
12.	You will pay all applicable federal, state and local taxes based on your provision of Rideshare Services and any payments received by you. 
13.	You agree to report any accidents, police reports, and incidents involving passengers and/or yourself while you are performing Vero 1 Ridesharing services to Vero 1 and your insurance company within 48 hours of the incident.   
14.	You agree that you will abide and comply with Vero 1 safety policies and strict “No weapons” policy for all of its properties including Vero1 hubs and services services.  
15.	You agree Vero 1 may reverse and deduct part or all of any payment to you if such payment was made in error, fraudulent, or illegal and/or that you did not render services in full accordance and compliance with Vero 1’s polices, terms, and conditions.    
16.	You agree to comply with your state’s dash cam, audio, and video recording rules and laws.  
Safety policies
Safety is our top priority. Learn more about Vero 1 's commitment to safety.
Review our policies regarding driver and passenger safety below.
Report safety issue or citation
Vero 1’s Safety response and Security team is available 24 hours a day, 7 days a week from the app and will call you as soon as possible after you request a call back.   This team is dedicated to the safety of both drivers and passengers and may be dispatched to your location if road-side assistance or security is needed.  However, this team is not a substitute for calling the police or 911 in the event of an emergency.   However, keep in mind that they will not be able to assist you with citations or tickets incurred outside of the Vero 1  platform, or due to violating standard traffic laws.

Skip to:
•	Age requirement
•	Weapons policy
•	Community Safety Education program
•	No-smoking policy
•	Recording device policy
•	Vero 1 ’s Approach to Arbitration and Confidentiality
Age requirement
Unaccompanied minors are prohibited from traveling with most carriers, including TNCs. A passenger must be 18 to sign up for a Vero 1  account, but if a driver believes a passenger might be underage, the driver may ask the passenger to confirm their age.
The driver may also let a passenger know that the driver will have to cancel the trip if the passenger is indeed under 18. In addition, drivers can report requests to transport unaccompanied minors by tapping 'Contact Support' below.
Back to top
Weapons policy
•	Vero 1  has a strict No Weapons policy for all of its properties. This includes Vero 1  Hubs and service centers. Vero 1’s No Weapons policy applies when you are doing business as a representative of Vero 1 , which includes times that you are driving for Vero 1, as well as times that you are visiting a Vero 1 office, center, or hub. This means that even in places where it is legal to carry a weapon, Vero 1 asks that you do not carry a weapon on any Vero 1 property.
•	We approach this from a community perspective. It's hard to know what someone else is or isn't comfortable with. The mere presence of a weapon might make another community member distressed and fear for his or her own personal safety.
•	At a minimum, a weapon includes any form of firearm. There are many items that could be considered weapons besides firearms, such as handguns, stun guns, explosives, knives, sling shots and tasers. Vero 1  reserves sole judgment on what else may constitute a weapon.  If you have any questions about whether various items could be considered a weapon under this policy, please contact Vero 1  Support before bringing any questionable items onto Vero 1  property.
•	Note: The general policy above does not apply to authorized security personnel contracted or employed by Vero 1  or to law enforcement personnel.
•	If you witnessed possession of a weapon in a Vero 1  vehicle, please let us know by tapping 'Contact Support' below. 
1.	Vero 1  Help
2.	About Vero 1 
3.	Safety, policies, and accessibility
4.	Safety guidelines and policies
5.	Safety policies
Community Safety Education program
Vero 1 is committed to holding each other accountable and to provide a safe and secure environment for both passengers and drivers. To educate our community about what's appropriate behavior in a Vero 1  ride and to prevent misbehavior, Vero 1 has developed a Community Safety Education 

This program empowers drivers to handle challenging passenger situation and create a safe and comfortable ride for everyone.  All Vero 1  drivers are required to complete this program in order to access Driver Mode.
Back to top
No-smoking policy
Smoking inside Vero 1 vehicles during rides is prohibited and against Vero 1 community rules for both drivers and passengers. There may be passengers entering the car who have respiratory issues or may be bothered by the smell, so in the spirit of respect for everyone in our community, Vero 1 asks that you refrain.  I
Back to top
Camera and Recording device policy

Vero 1 allows drivers to install and use video cameras, dashboard cams, or other recording devices to record riders for safety purposes and fulfilling transportation services. 

Please note that local regulations may require individuals using recording equipment in vehicles to fully disclose to riders that they are being recorded in or around a vehicle and obtain consent. Please check local regulations in your city to determine if these apply. 

In addition, our Community Guidelines do not allow users to use any other User's personal data for any reason other than for the purposes of fulfilling Transportation Services. They also specify that account access can be removed for conduct, language, or gestures that are disrespectful or unsafe. Broadcasting a person's image, audio, or video recording is a violation of these terms and may result in loss of account access.


Intellectual Property
All intellectual property rights in the Vero 1  Platform shall be owned by Vero 1  absolutely and in their entirety. These rights include database rights, copyright, design rights (whether registered or unregistered), trademarks (whether registered or unregistered) and other similar rights wherever existing in the world together with the right to apply for protection of the same. All other trademarks, logos, service marks, company or product names set forth in the Vero 1  Platform are the property of their respective owners. You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information (“Submissions”) provided by you to us are non-confidential and shall become the sole property of Vero 1. Vero 1  shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you. 
VERO 1  and other Vero 1  logos, designs, graphics, icons, scripts and service names are registered trademarks, trademarks or trade dress of Vero 1  in the United States and/or other countries (collectively, the “Vero 1  Marks”). If you provide Rideshare Services as a Driver, Vero 1  grants to you, during the term of this Agreement, and subject to your compliance with the terms and conditions of this Agreement, a limited, revocable, non-exclusive license to display and use the Vero 1  Marks solely on the Vero 1  stickers/decals, Vero 1  Amp, Vero 1 apparel, and any other Vero 1-branded items provided by Vero 1  directly to you in connection with providing the Rideshare Services (“License”).  The License is non-transferable and non-assignable, and you shall not grant to any third party any right, permission, license or sublicense with respect to any of the rights granted hereunder without Vero 1 ’s prior written permission, which it may withhold in its sole discretion. The Vero 1 logo (or any Vero 1  Marks) may not be used in any manner that is likely to cause confusion, including but not limited to: use of a Vero 1  Mark in a domain name or Vero 1  referral code, or use of a Vero 1  Mark as a social media handle or name, avatar, profile photo, icon, favicon, or banner. You may identify yourself as a Driver on the Vero 1  Platform, but may not misidentify yourself as Vero 1 , an employee of Vero 1 , or a representative of Vero 1 . 
You acknowledge that Vero 1 is the owner and licensor of the Vero 1 Marks, including all goodwill associated therewith, and that your use of the Vero 1  logo (or any Vero 1  Marks) will confer no interest in or ownership of the Vero 1  Marks in you but rather inures to the benefit of Vero 1 . You agree to use the Vero 1  logo strictly in accordance with Vero 1 ’s Brand Guidelines, as may be provided to you and revised from time to time, and to immediately cease any use that Vero 1  determines to nonconforming or otherwise unacceptable. 
You agree that you will not: (1) create any materials that use the Vero 1  Marks or any derivatives of the Vero 1  Marks as a trademark, service mark, trade name or trade dress, other than as expressly approved by Vero 1  in writing; (2) use the Vero 1  Marks in any way that tends to impair their validity as proprietary trademarks, service marks, trade names or trade dress, or use the Vero 1  Marks other than in accordance with the terms, conditions and restrictions herein; (3) take any other action that would jeopardize or impair Vero 1 ’s rights as owner of the Vero 1  Marks or the legality and/or enforceability of the Vero 1  Marks, including, challenging or opposing Vero 1 ’s ownership in the Vero 1  Marks; (4) apply for trademark registration or renewal of trademark registration of any of the Vero 1  Marks, any derivative of the Vero 1  Marks, any combination of the Vero 1  Marks and any other name, or any trademark, service mark, trade name, symbol or word which is similar to the Vero 1  Marks; (5) use the Vero 1  Marks on or in connection with any product, service or activity that is in violation of any law, statute, government regulation or standard. 
You agree you will not rent, lease, lend, sell, or otherwise redistribute the Vero 1  driver amp, or manufacture, produce, print, sell, distribute, purchase, or display counterfeit/inauthentic Vero 1  driver amps or other Vero 1  Marks or (including but not limited to signage, stickers, apparel, or decals) from any source other than directly from Vero 1 . 
Violation of any provision of this License may result in immediate termination of the License, in Vero 1 ’s sole discretion, a takedown request sent to the appropriate ISP, or social media platform, and/or a Uniform Domain-Name Dispute-Resolution Policy Proceeding (or equivalent proceeding). If you create any materials (physical or digital) bearing the Vero 1  Marks (in violation of this Agreement or otherwise), you agree that upon their creation Vero 1  exclusively owns all right, title and interest in and to such materials, including any modifications to the Vero 1  Marks or derivative works based on the Vero 1  Marks or Vero 1  copyrights. You further agree to assign any interest or right you may have in such materials to Vero 1 , and to provide information and execute any documents as reasonably requested by Vero 1  to enable Vero 1  to formalize such assignment. 
Vero 1  respects the intellectual property of others, and expects Users to do the same. If you believe, in good faith, that any materials on the Vero 1  Platform infringe upon your copyrights, please view our Copyright Policy for information on how to make a copyright complaint. 
Disclaimers
The following disclaimers are made on behalf of Vero 1 , our affiliates, subsidiaries, parents, successors and assigns, and each of our respective officers, directors, employees, agents, and shareholders. 
Vero 1  does not provide transportation services, and Vero 1  is not a transportation carrier. Vero 1  is not a common carrier or public carrier. It is up to the Driver to decide whether or not to offer a ride to a Rider contacted through the Vero 1  Platform, and it is up to the Rider to decide whether or not to accept a ride from any Driver contacted through the Vero 1  Platform. We cannot ensure that a Driver or Rider will complete an arranged transportation service. We have no control over the quality or safety of the transportation that occurs as a result of the Rideshare Services. 
The Vero 1  Platform is provided on an “as is” basis and without any warranty or condition, express, implied or statutory. We do not guarantee and do not promise any specific results from use of the Vero 1  Platform and/or the Rideshare Services, including the ability to provide or receive Rideshare Services at any given location or time. Vero 1  reserves the right, for example, to limit or eliminate access to the Vero 1  Platform for Rideshare Services in specific geographic areas and/or at specific times based on commercial viability, public health concerns, or changes in law. To the fullest extent permitted by law, we specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. Some states do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not apply to you. 
We do not warrant that your use of the Vero 1  Platform or Rideshare Services will be accurate, complete, reliable, current, secure, uninterrupted, always available, or error-free, or will meet your requirements, that any defects in the Vero 1  Platform will be corrected, or that the Vero 1  Platform is free of viruses or other harmful components. We disclaim liability for, and no warranty is made with respect to, connectivity and availability of the Vero 1  Platform or Rideshare Services. 
We cannot guarantee that each Rider or Driver is who he or she claims to be. Please use common sense when using the Vero 1  Platform and Rideshare Services, including looking at the photos of the Driver or Rider you have matched with to make sure it is the same individual you see in person. Please note that there are also risks of dealing with underage persons or people acting under false pretense, and we do not accept responsibility or liability for any content, communication or other use or access of the Vero 1  Platform by persons under the age of 18 in violation of this Agreement. We encourage you to communicate directly with each potential Driver or Rider prior to engaging in an arranged transportation service. 
Vero 1  is not responsible for the conduct, whether online or offline, of any User of the Vero 1  Platform or Rideshare Services. You are solely responsible for your interactions with other Users. We do not procure insurance for, nor are we responsible for, personal belongings left in the car by Drivers or Riders. By using the Vero 1  Platform and participating in the Rideshare Services, you agree to accept such risks and agree that Vero 1  is not responsible for the acts or omissions of Users on the Vero 1  Platform or participating in the Rideshare Services. 
You are responsible for the use of your User account and Vero 1  expressly disclaims any liability arising from the unauthorized use of your User account. Should you suspect that any unauthorized party may be using your User account or you suspect any other breach of security, you agree to notify us immediately. 
It is possible for others to obtain information about you that you provide, publish or post to or through the Vero 1  Platform (including any profile information you provide), send to other Users, or share during the Rideshare Services, and to use such information to harass or harm you. We are not responsible for the use of any personal information that you disclose to other Users on the Vero 1  Platform or through the Rideshare Services. Please carefully select the type of information that you post on the Vero 1  Platform or through the Rideshare Services or release to others. We disclaim all liability, regardless of the form of action, for the acts or omissions of other Users (including unauthorized users, or “hackers”). 
Opinions, advice, statements, offers, or other information or content concerning Vero 1  or made available through the Vero 1  Platform, but not directly by us, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. Under no circumstances will we be responsible for any loss or damage resulting from your reliance on information or other content posted by third parties, whether on the Vero 1  Platform or otherwise. We reserve the right, but we have no obligation, to monitor the materials posted on the Vero 1  Platform and remove any such material that in our sole opinion violates, or is alleged to violate, the law or this agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of Users or others. 
Location data provided by the Vero 1  Platform is for basic location purposes only and is not intended to be relied upon in situations where precise location information is needed or where erroneous, inaccurate or incomplete location data may lead to death, personal injury, property or environmental damage. Neither Vero 1 , nor any of its content providers, guarantees the availability, accuracy, completeness, reliability, or timeliness of location data tracked or displayed by the Vero 1  Platform. Any of your Information, including geolocational data, you upload, provide, or post on the Vero 1  Platform may be accessible to Vero 1  and certain Users of the Vero 1  Platform. 
Vero 1  advises you to use the Vero 1  Platform with a data plan with unlimited or very high data usage limits, and Vero 1  shall not be responsible or liable for any fees, costs, or overage charges associated with any data plan you use to access the Vero 1  Platform. 
This paragraph applies to any version of the Vero 1  Platform that you acquire from the Apple App Store. This Agreement is entered into between you and Vero 1 . Apple, Inc. (“Apple”) is not a party to this Agreement and shall have no obligations with respect to the Vero 1  Platform. Vero 1 , not Apple, is solely responsible for the Vero 1  Platform and the content thereof as set forth hereunder. However, Apple and Apple’s subsidiaries are third-party beneficiaries of this Agreement. Upon your acceptance of this Agreement, Apple shall have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as a third-party beneficiary thereof. This Agreement incorporates by reference Apple’s Licensed Application End User License Agreement, for purposes of which, you are “the end-user.” In the event of a conflict in the terms of the Licensed Application End User License Agreement and this Agreement, the terms of this Agreement shall control. 
As a Driver, you may be able to use Vero 1  Nav built by Google while providing Rideshare Services on the Platform. Riders and Drivers may also use Google Maps while using the Vero 1  App. In either case, you agree that Google may collect your location data when the Vero 1  App is running in order to provide and improve Google's services, that such data may also be shared with Vero 1  in order to improve its operations, and that Google's terms and privacy policy will apply to this usage. 
Vero 1  shall not be in breach of this Agreement nor liable for failure or delay in performing obligations under this Agreement if such failure or delay results from events, circumstances or causes beyond its reasonable control including (without limitation) natural disasters or acts of God; acts of terrorism; labor disputes or stoppages; war; government action; epidemic or pandemic; chemical or biological contamination; strikes, riots, or acts of domestic or international terrorism; quarantines; national or regional emergencies; or any other cause, whether similar in kind to the foregoing or otherwise, beyond the party’s reasonable control. All service dates under this Agreement affected by force majeure shall be tolled for the duration of such force majeure. The parties hereby agree, when feasible, not to cancel but reschedule the pertinent obligations as soon as practicable after the force majeure condition ceases to exist. 
State and Local Disclosures
Certain jurisdictions require additional disclosures to you. You can view any disclosures required by your local jurisdiction at www.Vero 1 .com/terms/disclosures. We will update the disclosures page as jurisdictions add, remove or amend these required disclosures, so please check in regularly for updates. 
Indemnity
You will defend, indemnify, and hold Vero 1  including our affiliates, subsidiaries, parents, successors and assigns, and each of our respective officers, directors, employees, agents, or shareholders harmless from any claims, actions, suits, losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of your use of the Vero 1  Platform and participation in the Rideshare Services, including: (1) your breach of this Agreement or the documents it incorporates by reference; (2) your violation of any law or the rights of a third party, including, Drivers, Riders, other motorists, and pedestrians, as a result of your own interaction with such third party; (3) any allegation that any materials that you submit to us or transmit through the Vero 1  Platform or to us infringe or otherwise violate the copyright, trademark, trade secret or other intellectual property or other rights of any third party; (4) your ownership, use or operation of a motor vehicle or passenger vehicle, including your provision of Rideshare Services as a Driver; and/or (5) any other activities in connection with the Rideshare Services. This indemnity shall be applicable without regard to the negligence of any party, including any indemnified person. 
Limitation of Liability
IN NO EVENT WILL VERO 1 , INCLUDING OUR AFFILIATES, SUBSIDIARIES, PARENTS, SUCCESSORS AND ASSIGNS, AND EACH OF OUR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR SHAREHOLDERS (COLLECTIVELY “VERO 1 ” FOR PURPOSES OF THIS SECTION), BE LIABLE TO YOU FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, CONSEQUENTIAL, OR INDIRECT DAMAGES (INCLUDING DAMAGES FOR DELETION, CORRUPTION, LOSS OF DATA, LOSS OF PROGRAMS, FAILURE TO STORE ANY INFORMATION OR OTHER CONTENT MAINTAINED OR TRANSMITTED BY THE VERO 1 PLATFORM, SERVICE INTERRUPTIONS, OR FOR THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES) ARISING OUT OF OR IN CONNECTION WITH THE VERO 1  PLATFORM, RIDESHARE SERVICES, OR THIS AGREEMENT, HOWEVER ARISING INCLUDING NEGLIGENCE, EVEN IF WE OR OUR AGENTS OR REPRESENTATIVES KNOW OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  THE VERO 1 PLATFORM MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS, OR OTHER SERVICES WITH THIRD-PARTY PROVIDERS, BUT YOU AGREE THAT VERO 1  HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY TRANSPORTATION, GOODS OR OTHER SERVICES PROVIDED TO YOU BY THIRD PARTY PROVIDERS OTHER THAN AS EXPRESSLY SET FORTH IN IN THIS AGREEMENT. CERTAIN JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS. 
Term and Termination
This Agreement is effective upon your acceptance of this Agreement. This Agreement may be terminated: a) by User, without cause, upon seven (7) days’ prior written notice to Vero 1 ; or b) by either Party immediately, without notice, upon the other Party’s material breach of this Agreement, including but not limited to any breach of Section 9 or breach of Section 10(a) through (i) of this Agreement. In addition, Vero 1  may terminate this Agreement or deactivate your User account immediately in the event: (1) you no longer qualify to provide Rideshare Services or to operate the approved vehicle under applicable law, rule, permit, ordinance or regulation; (2) you fall below Vero 1 ’s star rating or cancellation threshold; (3) Vero 1  has the good faith belief that such action is necessary to protect the safety of the Vero 1  community or third parties, provided that in the event of a deactivation pursuant to (1)-(3) above, you will be given notice of the potential or actual deactivation and an opportunity to attempt to cure the issue to Vero 1 ’s reasonable satisfaction prior to Vero 1  permanently terminating the Agreement. For all other breaches of this Agreement, you will be provided notice and an opportunity to cure the breach. If the breach is cured in a timely manner and to Vero 1 ’s satisfaction, this Agreement will not be permanently terminated. Sections 2, 6, 7 (with respect to the license), 11-12, 14-19, and 21 shall survive any termination or expiration of this Agreement. 
Dispute Resolution and Arbitration Agreement
(a) Agreement to Binding Arbitration Between You and Vero 1 . 
YOU AND VERO 1  MUTUALLY AGREE TO WAIVE OUR RESPECTIVE RIGHTS TO RESOLUTION OF DISPUTES IN A COURT OF LAW BY A JUDGE OR JURY AND AGREE TO RESOLVE ANY DISPUTE BY ARBITRATION, as set forth below. This agreement to arbitrate (“Arbitration Agreement”) is governed by the Federal Arbitration Act (“FAA”); but if the FAA is inapplicable for any reason, then this Arbitration Agreement is governed by the laws of the State of Delaware, including Del. Code tit. 10, § 5701 et seq., without regard to choice of law principles. This Arbitration Agreement survives after the Agreement terminates or your relationship with Vero 1 ends. ANY ARBITRATION UNDER THIS AGREEMENT WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED. Except as expressly provided below, this Arbitration Agreement applies to all Claims (defined below) between you and Vero 1 , including our affiliates, subsidiaries, parents, successors and assigns, and each of our respective officers, directors, employees, agents, or shareholders. This Arbitration Agreement also applies to claims between you and Vero 1 ’s service providers, including but not limited to background check providers and payment processors; and such service providers shall be considered intended third-party beneficiaries of this Arbitration Agreement. 
Except as expressly provided below, ALL DISPUTES AND CLAIMS BETWEEN US (EACH A “CLAIM” AND COLLECTIVELY, “CLAIMS”) SHALL BE EXCLUSIVELY RESOLVED BY BINDING ARBITRATION SOLELY BETWEEN YOU AND VERO 1 . These Claims include, but are not limited to, any dispute, claim or controversy, whether based on past, present, or future events, arising out of or relating to: this Agreement and prior versions thereof (including the breach, termination, enforcement, interpretation or validity thereof), the Vero 1  Platform, the Rideshare Services, rental or use of bikes or scooters through the Vero 1  Platform, Vero 1  promotions, gift card, referrals or loyalty programs, any other goods or services made available through the Vero 1  Platform, your relationship with Vero 1 , the threatened or actual suspension, deactivation or termination of your User Account or this Agreement, background checks performed by or on Vero 1 ’s behalf, payments made by you or any payments made or allegedly owed to you, any promotions or offers made by Vero 1 , any city, county, state or federal wage-hour law, trade secrets, unfair competition, compensation, breaks and rest periods, expense reimbursement, wrongful termination, discrimination, harassment, retaliation, fraud, defamation, emotional distress, breach of any express or implied contract or covenant, claims arising under federal or state consumer protection laws; claims arising under antitrust laws, claims arising under the Telephone Consumer Protection Act and Fair Credit Reporting Act; and claims arising under the Uniform Trade Secrets Act, Civil Rights Act of 1964, Americans With Disabilities Act, Age Discrimination in Employment Act, Older Workers Benefit Protection Act, Family Medical Leave Act, Fair Labor Standards Act, Employee Retirement Income Security Act of 1974 (except for individual claims for employee benefits under any benefit plan sponsored by Vero 1  and covered by the Employee Retirement Income Security Act of 1974 or funded by insurance), and state statutes, if any, addressing the same or similar subject matters, and all other federal and state statutory and common law claims. All disputes concerning the arbitrability of a Claim (including disputes about the scope, applicability, enforceability, revocability or validity of the Arbitration Agreement) shall be decided by the arbitrator, except as expressly provided below. 
BY AGREEING TO ARBITRATION, YOU UNDERSTAND THAT YOU AND VERO 1  ARE WAIVING THE RIGHT TO SUE IN COURT OR HAVE A JURY TRIAL FOR ALL CLAIMS, EXCEPT AS EXPRESSLY OTHERWISE PROVIDED IN THIS ARBITRATION AGREEMENT. This Arbitration Agreement is intended to require arbitration of every claim or dispute that can lawfully be arbitrated, except for those claims and disputes which by the terms of this Arbitration Agreement are expressly excluded from the requirement to arbitrate. 
(b) Prohibition of Class Actions and Non-Individualized Relief. 
You understand and agree that you and Vero 1 may each bring Claims in arbitration against the other only in an individual capacity and not on a class, collective action, or representative basis (“Class Action Waiver”). You understand and agree that you and Vero 1  both are waiving the right to pursue or have a dispute resolved as a plaintiff or class member in any purported class, collective or representative proceeding. Notwithstanding the foregoing, this subsection (b) shall not apply to representative private attorneys general act claims brought against Vero 1 , which are addressed separately in Section 17(c). 
The arbitrator shall have no authority to consider or resolve any Claim or issue any relief on any basis other than an individual basis. The arbitrator shall have no authority to consider or resolve any Claim or issue any relief on a class, collective, or representative basis. The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claims. 
Notwithstanding any other provision of this Agreement, the Arbitration Agreement or the AAA Rules, disputes regarding the interpretation, applicability, or enforceability of the Class Action Waiver may be resolved only by a court and not by an arbitrator. In any case in which: (1) the dispute is filed as a class, collective, or representative action and (2) there is a final judicial determination that the Class Action Waiver is unenforceable with respect to any Claim or any particular remedy for a Claim (such as a request for public injunctive relief), then that Claim or particular remedy (and only that Claim or particular remedy) shall be severed from any remaining claims and/or remedies and may be brought in a court of competent jurisdiction, but the Class Action Waiver shall be enforced in arbitration on an individual basis as to all other Claims or remedies to the fullest extent possible. 
(c) Representative PAGA Waiver. 
Notwithstanding any other provision of this Agreement or the Arbitration Agreement, to the fullest extent permitted by law: (1) you and Vero 1  agree not to bring a representative action on behalf of others under the Private Attorneys General Act of 2004 (“PAGA”), California Labor Code § 2698 et seq., in any court or in arbitration, and (2) for any claim brought on a private attorney general basis, including under the California PAGA, both you and Vero 1  agree that any such dispute shall be resolved in arbitration on an individual basis only (i.e., to resolve whether you have personally been aggrieved or subject to any violations of law), and that such an action may not be used to resolve the claims or rights of other individuals in a single or collective proceeding (i.e., to resolve whether other individuals have been aggrieved or subject to any violations of law) (collectively, “representative PAGA Waiver”). Notwithstanding any other provision of this Agreement, the Arbitration Agreement or the AAA Rules, disputes regarding the scope, applicability, enforceability, revocability or validity of this representative PAGA Waiver may be resolved only by a civil court of competent jurisdiction and not by an arbitrator. If any provision of this representative PAGA Waiver is found to be unenforceable or unlawful for any reason: (i) the unenforceable provision shall be severed from this Agreement; (ii) severance of the unenforceable provision shall have no impact whatsoever on the Arbitration Agreement or the requirement that any remaining Claims be arbitrated on an individual basis pursuant to the Arbitration Agreement; and (iii) any such representative PAGA or other representative private attorneys general act claims must be litigated in a civil court of competent jurisdiction and not in arbitration. To the extent that there are any Claims to be litigated in a civil court of competent jurisdiction because a civil court of competent jurisdiction determines that the representative PAGA Waiver is unenforceable with respect to those Claims, the Parties agree that litigation of those Claims shall be stayed pending the outcome of any individual Claims in arbitration. 
(d) Rules Governing the Arbitration. 
Any arbitration conducted pursuant to this Arbitration Agreement shall be administered by the American Arbitration Association (“AAA”) pursuant to its Consumer Arbitration Rules that are in effect at the time the arbitration is initiated, as modified by the terms set forth in this Agreement. Copies of these rules can be obtained at the AAA’s website (www.adr.org) (the “AAA Rules”). Notwithstanding the foregoing, if requested by you and if proper based on the facts and circumstances of the Claims presented, the arbitrator shall have the discretion to select a different set of AAA Rules, but in no event shall the arbitrator consolidate more than one person’s Claims, or otherwise preside over any form of representative, collective, or class proceeding. The parties may select a different arbitration administrator upon mutual written agreement. 
As part of the arbitration, both you and Vero 1  will have the opportunity for reasonable discovery of non-privileged information that is relevant to the Claim. The arbitrator may award any individualized remedies that would be available in court. The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claims. The arbitrator will provide a reasoned written statement of the arbitrator’s decision which shall explain the award given and the findings and conclusions on which the decision is based. 
The arbitrator will decide the substance of all claims in accordance with applicable law, and will honor all claims of privilege recognized by law. The arbitrator shall not be bound by rulings in prior arbitrations involving different Riders or Drivers, but is bound by rulings in prior arbitrations involving the same Rider or Driver to the extent required by applicable law. The arbitrator’s award shall be final and binding and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof, provided that any award may be challenged in a court of competent jurisdiction. 
(e) Arbitration Fees and Awards. 
The payment of filing and arbitration fees will be governed by the relevant AAA Rules subject to the following modifications: 
1.	If Vero 1  initiates arbitration under this Arbitration Agreement, Vero 1  will pay all AAA filing and arbitration fees. 
2.	With respect to any Claims brought by Vero 1  against a Driver, or for Claims brought by a Driver against Vero 1  that: (A) are based on an alleged employment relationship between Vero 1  and a Driver; (B) arise out of, or relate to, Vero 1 ’s actual deactivation of a Driver’s User account or a threat by Vero 1  to deactivate a Driver’s User account; (C) arise out of, or relate to, Vero 1 ’s actual termination of a Driver’s Agreement with Vero 1  under the termination provisions of this Agreement, or a threat by Vero 1  to terminate a Driver’s Agreement; (D) arise out of, or relate to, Fares (as defined in this Agreement, including Vero 1 ’s commission or fees on the Fares), tips, or average hourly guarantees owed by Vero 1  to Drivers for Rideshare Services, other than disputes relating to referral bonuses, other Vero 1  promotions, or consumer-type disputes, or (E) arise out of or relate to background checks performed in connection with a user seeking to become a Driver (the subset of Claims in subsections (A)-(E) shall be collectively referred to as “Driver Claims”), Vero 1  shall pay all costs unique to arbitration (as compared to the costs of adjudicating the same claims before a court), including the regular and customary arbitration fees and expenses (to the extent not paid by Vero 1  pursuant to the fee provisions above). However, if you are the party initiating the Driver Claim, you shall be responsible for contributing up to an amount equal to the filing fee that would be paid to initiate the claim in the court of general jurisdiction in the state in which you provide Rideshare Services to Riders, unless a lower fee amount would be owed by you pursuant to the AAA Rules, applicable law, or subsection (e)(1) above. Any dispute as to whether a cost is unique to arbitration shall be resolved by the arbitrator. For purposes of this Section 17(e)(2), the term “Driver” shall be deemed to include both Drivers and Driver applicants who have not been approved to drive. 
3.	Except as provided in Federal Rule of Civil Procedure 68 or any state equivalents, each party shall pay its own attorneys’ fees and pay any costs that are not unique to the arbitration (i.e., costs that each party would incur if the claim(s) were litigated in a court such as costs to subpoena witnesses and/or documents, take depositions and purchase deposition transcripts, copy documents, etc.). 
4.	At the end of any arbitration, the arbitrator may award reasonable fees and costs or any portion thereof to you if you prevail, to the extent authorized by applicable law. 
5.	Although under some laws Vero 1  may have a right to an award of attorneys' fees and non-filing fee expenses if it prevails in an arbitration, Vero 1  agrees that it will not seek such an award unless you are represented by an attorney or the arbitrator has determined that the claim is frivolous or brought for an improper purpose (as measured by the standards of Federal Rule of Civil Procedure 11(b)). 
6.	If the arbitrator issues you an award that is greater than the value of Vero 1 ’s last written settlement offer made after you participated in good faith in the optional Negotiation process described in subsection (k) below, then Vero 1  will pay you the amount of the award or U.S. $1,000, whichever is greater. 
(f) Location and Manner of Arbitration. 
Unless you and Vero 1  agree otherwise, any arbitration hearings between Vero 1  and a Rider will take place in the county of your billing address, and any arbitration hearings between Vero 1  and a Driver will take place in the county in which the Driver provides Rideshare Services. If AAA arbitration is unavailable in your county, the arbitration hearings will take place in the nearest available location for a AAA arbitration. Your right to a hearing will be determined by the AAA Rules. 
(g) Exceptions to Arbitration. 
This Arbitration Agreement shall not require arbitration of the following types of claims: (1) small claims actions brought on an individual basis that are within the scope of such small claims court’s jurisdiction; (2) a representative action brought on behalf of others under PAGA or other private attorneys general acts, to the extent the representative PAGA Waiver in Section 17(c) of such action is deemed unenforceable by a court of competent jurisdiction under applicable law not preempted by the FAA; (3) claims for workers’ compensation, state disability insurance and unemployment insurance benefits; (4) claims that may not be subject to arbitration as a matter of generally applicable law not preempted by the FAA; and (5) individual claims of sexual assault or sexual harassment in connection with the use of the Vero 1  Platform or Rideshare Services. Where these claims are brought in a court of competent jurisdiction, Vero 1  will not require arbitration of those claims. Vero 1 's agreement not to require arbitration of these claims does not waive the enforceability of any other provision of this Arbitration Agreement (including without limitation the waivers provided in Section 17(b)), or of the enforceability of this Arbitration Agreement as to any other dispute, claim, or controversy. 
Nothing in this Arbitration Agreement prevents you from making a report to or filing a claim or charge with the Equal Employment Opportunity Commission, U.S. Department of Labor, Securities Exchange Commission, National Labor Relations Board (“NLRB”), or Office of Federal Contract Compliance Programs, or similar local, state or federal agency, and nothing in this Arbitration Agreement shall be deemed to preclude or excuse a party from bringing an administrative claim before any agency in order to fulfill the party's obligation to exhaust administrative remedies before making a claim in arbitration However, should you bring an administrative claim, you may only seek or recover money damages of any type pursuant to this Arbitration Provision, and you knowingly and voluntarily waive the right to seek or recover money damages of any type pursuant to any administrative complaint, except for a complaint issued by the NLRB. Should you participate in an NLRB proceeding, you may only recover money damages if such recovery does not arise from or relate to a claim previously adjudicated under this Arbitration Provision or settled by you. Similarly, you may not recover money damages under this Arbitration Provision if you have already adjudicated such claim with the NLRB. Nothing in this Agreement or Arbitration Agreement prevents your participation in an investigation by a government agency of any report, claim or charge otherwise covered by this Arbitration Provision. 
(h) Severability. 
Except as otherwise provided in the severability provisions in subsections (b) and (c) above, in the event that any portion of this Arbitration Agreement is deemed illegal or unenforceable under applicable law not preempted by the FAA, such provision shall be severed and the remainder of the Arbitration Agreement shall be given full force and effect. 
(i) Driver Claims in Pending Settlement. 
If you are a member of a putative class in a lawsuit against Vero 1  involving Driver Claims and a Motion for Preliminary Approval of a Settlement has been filed with the court in that lawsuit prior to this Agreement’s effective date (a “Pending Settlement Action”), then this Arbitration Agreement shall not apply to your Driver Claims in that particular class action. Instead, your Driver Claims in that Pending Settlement Action shall continue to be governed by the arbitration provisions contained in the applicable Agreement that you accepted prior to this Agreement’s effective date. 
(j) Opting Out of Arbitration for Driver Claims That Are Not In a Pending Settlement Action. 
As a Driver or Driver applicant, you may opt out of the requirement to arbitrate Driver Claims defined in Section 17(e)(2) (except as limited by Section 17(i) above) pursuant to the terms of this subsection if you have not previously agreed to an arbitration provision in Vero 1 ’s Terms of Service where you had the opportunity to opt out of the requirement to arbitrate. If you have previously agreed to such an arbitration provision, you may opt out of any revisions to your prior arbitration agreement made by this provision in the manner specified below, but opting out of this arbitration provision has no effect on any previous, other, or future arbitration agreements that you may have with Vero 1 . If you have not previously agreed to such an arbitration provision and do not wish to be subject to this Arbitration Agreement with respect to Driver Claims, you may opt out of arbitration with respect to such Driver Claims, other than those in a Pending Settlement Action, by notifying Vero 1  in writing of your desire to opt out of arbitration for such Driver Claims, which writing must be dated, signed and delivered by electronic mail to arbitrationoptout@Vero 1 .com. 
In order to be effective, (A) the writing must clearly indicate your intent to opt out of this Arbitration Agreement with respect to Driver Claims that are not part of a Pending Settlement Action, (B) the writing must include the name, phone number, and email address associated with your User Account, and (C) the email containing the signed writing must be sent within 30 days of the date this Agreement is executed by you. Should you not opt out within the 30-day period, you and Vero 1  shall be bound by the terms of this Arbitration Agreement in full (including with respect to Driver Claims that are not part of a Pending Settlement Action). As provided in paragraph 17(i) above, any opt out that you submit shall not apply to any Driver Claims that are part of a Pending Settlement Action and your Driver Claims in any such Pending Settlement Action shall continue to be governed by the arbitration provisions that are contained in the applicable Vero 1  Terms of Use that you agreed to prior to the effective date of this Agreement. 
Cases may be filed in the future involving Driver Claims. You should assume that there may be in the future, lawsuits against Vero 1  alleging class, collective, and/or representative Driver Claims in which the plaintiffs seek to act on your behalf, and which, if successful, could result in some monetary recovery to you. But if you do agree to arbitration of Driver Claims with Vero 1  under this Arbitration Agreement, you are agreeing in advance that you will bring all such claims, and seek all monetary and other relief, against Vero 1  in an individual arbitration, except for the Driver Claims that are part of a Pending Settlement Action. You are also agreeing in advance that you will not participate in, or seek to recover monetary or other relief, for such claims in any court action or class, collective, and/or representative action. You have the right to consult with counsel of your choice concerning this Arbitration Agreement and you will not be subject to retaliation if you exercise your right to assert claims or opt-out of any Driver Claims under this Arbitration Agreement. 
(k) Optional Pre-Arbitration Negotiation Process. 
Before initiating any arbitration or proceeding, you and Vero 1  may agree to first attempt to negotiate any dispute, claim or controversy between the parties informally for 30 days, unless this time period is mutually extended by you and Vero 1 . A party who intends to seek negotiation under this subsection must first send to the other a written notice of the dispute (“Notice”). The Notice must (1) describe the nature and basis of the claim or dispute; and (2) set forth the specific relief sought. All offers, promises, conduct and statements, whether oral or written, made in the course of the negotiation by any of the parties, their agents, employees, and attorneys are confidential, privileged and inadmissible for any purpose, including as evidence of liability or for impeachment, in arbitration or other proceeding involving the parties, provided that evidence that is otherwise admissible or discoverable shall not be rendered inadmissible or non-discoverable as a result of its use in the negotiation. 
Confidentiality
You agree not to use any technical, financial, strategic and other proprietary and confidential information relating to Vero 1 ’s business, operations and properties, information about a User made available to you in connection with such User’s use of the Platform, which may include the User’s name, pick-up location, contact information and photo (“Confidential Information”) disclosed to you by Vero 1  for your own use or for any purpose other than as contemplated herein. You shall not disclose or permit disclosure of any Confidential Information to third parties, and you agree not to store separate and outside of the Vero 1  Platform any User Information obtained from the Vero 1  Platform. As a Driver, you understand that some of Rider Information you receive may be protected by federal and/or state confidentiality laws, such as the Health Information Portability and Accountability Act of 1996 (“HIPAA”), governing the privacy and security of protected (patient) health information. In the event that you know a Rider, you should not disclose to anyone the identity of the Rider or the location that you picked up, or dropped off the Rider, as this could violate HIPAA. You understand that any violation of the Agreement’s confidentiality provisions may violate HIPAA or state confidentiality laws and could result in civil or criminal penalties against you. You agree to take all reasonable measures to protect the secrecy of and avoid disclosure or use of Confidential Information of Vero 1  in order to prevent it from falling into the public domain. Notwithstanding the above, you shall not have liability to Vero 1  with regard to any Confidential Information which you can prove: was in the public domain at the time it was disclosed by Vero 1  or has entered the public domain through no fault of yours; was known to you, without restriction, at the time of disclosure, as demonstrated by files in existence at the time of disclosure; is disclosed with the prior written approval of Vero 1 ; becomes known to you, without restriction, from a source other than Vero 1  without breach of this Agreement by you and otherwise not in violation of Vero 1 ’s rights; or is disclosed pursuant to the order or requirement of a court, administrative agency, or other governmental body; provided, however, that You shall provide prompt notice of such court order or requirement to Vero 1  to enable Vero 1  to seek a protective order or otherwise prevent or restrict such disclosure. 
Relationship with Vero 1 
As a Driver on the Vero 1  Platform, you acknowledge and agree that you and Vero 1  are in a direct business relationship, and the relationship between the parties under this Agreement is solely that of independent contracting parties. You and Vero 1  expressly agree that (1) this is not an employment agreement and does not create an employment relationship between you and Vero 1 ; and (2) no joint venture, franchisor-franchisee, partnership, or agency relationship is intended or created by this Agreement. You have no authority to bind Vero 1 , and you undertake not to hold yourself out as an employee, agent or authorized representative of Vero 1 . 
Vero 1  does not, and shall not be deemed to, direct or control you generally or in your performance under this Agreement specifically, including in connection with your provision of Rideshare Services, your acts or omissions, or your operation and maintenance of your vehicle. You retain the sole right to determine when, where, and for how long you will utilize the Vero 1  Platform. Vero 1  does not, and shall not be deemed to, unilaterally prescribe specific dates, times of day, or any minimum number of hours for you to utilize the Vero 1  Platform. You retain the option to accept or to decline or ignore a Rider’s request for Rideshare Services via the Vero 1  Platform, or to cancel an accepted request for Rideshare Services via the Vero 1  Platform, subject to Vero 1 ’s then-current cancellation policies. Vero 1  does not, and shall not be deemed to, require you to accept any specific request for Rideshare Services as a condition of maintaining access to the platform. With the exception of any signage required by law or permit/license rules or requirements, Vero 1  shall have no right to require you to: (a) display Vero 1 ’s names, logos or colors on your vehicle(s); or (b) wear a uniform or any other clothing displaying Vero 1 ’s names, logos or colors. You acknowledge and agree that you have complete discretion to provide Rideshare Services or otherwise engage in any other business or employment activities, including but not limited to providing services similar to the Rideshare Services to other companies, and that Vero 1  does not, and shall not be deemed to, restrict you from engaging in any such activity. 
Other Services
In addition to connecting Riders with Drivers, the Vero 1  Platform may enable Users to provide or receive services from other third parties. For example, Users may be able to use the Vero 1  Platform to plan and reserve rides on public transportation, take a ride in an autonomous vehicle provided by a third party, rent vehicles, or obtain financial services provided by third parties (collectively, the “Other Services”). You understand that the Other Services are subject to the terms and pricing of the third-party provider. If you choose to purchase Other Services through the Vero 1  Platform, you authorize Vero 1  to charge your payment method on file according to the pricing terms set by the third-party provider. You agree that Vero 1  is not responsible and may not be held liable for the Other Services or the actions or omissions of the third-party provider. Such Other Services may not be investigated, monitored or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Other Services accessed through the Vero 1  Platform. This Agreement incorporates by reference ADT Mobile Security Monitoring Terms. In the event of a conflict in the terms of the ADT Mobile Security Monitoring Terms and this Agreement, the terms of this Agreement shall control with respect to Vero 1  and your agreements with Vero 1  herein, and the limitations of liability set forth in Section 15 above shall also apply to ADT. The Dispute Resolution and Arbitration Agreement provisions in Section 17 above shall apply instead of any terms in the ADT Mobile Security Monitoring Terms for all purposes except with respect to claims that are solely against ADT. 
General
Except as provided in Section 17, this Agreement shall be governed by the laws of the State of California without regard to choice of law principles. This choice of law provision is only intended to specify the use of California law to interpret this Agreement and is not intended to create any other substantive right to non- Californians to assert claims under California law whether by statute, common law, or otherwise. If any provision of this Agreement is or becomes invalid or non- binding, the parties shall remain bound by all other provisions of this Agreement. In that event, the parties shall replace the invalid or non-binding provision with provisions that are valid and binding and that have, to the greatest extent possible, a similar effect as the invalid or non-binding provision, given the contents and purpose of this Agreement. You agree that this Agreement and all incorporated agreements may be automatically assigned by Vero 1 , in our sole discretion by providing notice to you. Except as explicitly stated otherwise, any notices to Vero 1  shall be given by certified mail, postage prepaid and return receipt requested to Vero 1 , Inc., 548 Market Street, #68514 San Francisco, CA 94104. Any notices to you shall be provided to you through the Vero 1  Platform or given to you via the email address or physical you provide to Vero 1  during the registration process. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. The words “include”, “includes” and “including” are deemed to be followed by the words “without limitation”. A party’s failure to act with respect to a breach by the other party does not constitute a waiver of the party’s right to act with respect to subsequent or similar breaches. This Agreement sets forth the entire understanding and agreement between you and Vero 1  with respect to the subject matter hereof and supersedes all previous understandings and agreements between the parties, whether oral or written. 
If you have any questions regarding the Vero 1  Platform or Rideshare Services, please contact us through our Help Center. 
"/>
      </View>
  );
}

export default TermsConditions;